my_list=[1,2,"hello",4.5]
print(my_list)
my_list.append("bye bye")
print(my_list)
my_list.pop(3)
print(my_list)
my_list.pop()
print(my_list)
print(len(my_list))
my_list.append(5)
my_list.append(5)
my_list.append(5)
my_list.append(5)
print(my_list)
print(my_list.count(5))
my_list.insert(1,"Yo")
print(my_list)
print(my_list[-1])